# Generated by Django 3.0.6 on 2020-06-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_auto_20200602_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emails',
            field=models.EmailField(default='user@gmail.com', max_length=254),
        ),
    ]
