# Generated by Django 3.0.6 on 2020-06-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_profile_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prop_no',
            field=models.IntegerField(default='-1'),
        ),
    ]
