# Generated by Django 3.0.6 on 2020-06-04 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_app', '0008_profile_prop_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emails', models.EmailField(default='user@gmail.com', max_length=254)),
                ('image', models.ImageField(default='default.jpeg', upload_to='profile_pic')),
                ('pdfs', models.FileField(default='user.pdf', upload_to='props/pdfs')),
                ('prop_no', models.IntegerField(default='-1')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Mentors', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
