# Generated by Django 3.0.6 on 2020-06-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='propsl_list',
            field=models.CharField(default='0', max_length=300),
        ),
    ]
