# Generated by Django 3.0.6 on 2020-06-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_profile_propsl_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='propsl_list',
            field=models.CharField(max_length=300),
        ),
    ]
