# Generated by Django 3.0.6 on 2020-06-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_auto_20200604_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='propsl_list',
            field=models.CharField(default='0', max_length=300),
        ),
    ]
