# Generated by Django 3.0.6 on 2020-06-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_mentors_propsl_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors',
            name='prop_no',
            field=models.IntegerField(default='-1', max_length=10),
        ),
    ]
