# Generated by Django 3.0.6 on 2020-06-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_auto_20200605_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentors',
            name='prop_no',
            field=models.CharField(default='-1', max_length=10),
        ),
    ]
