# Generated by Django 3.0.6 on 2020-06-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_auto_20200605_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
