# Generated by Django 3.0.6 on 2020-06-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0020_mentors_full_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='no text', max_length=200)),
                ('ids', models.CharField(default='no id', max_length=10)),
                ('summary', models.CharField(default='no summary', max_length=200)),
                ('svm_categories', models.CharField(default='no svm categories', max_length=200)),
                ('text', models.CharField(default='no text', max_length=2000)),
                ('title', models.CharField(default='no title', max_length=50)),
            ],
        ),
    ]
