# Generated by Django 3.0.6 on 2020-06-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0021_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='skills',
            field=models.CharField(default='no skills', max_length=300),
        ),
    ]
