# Generated by Django 3.0.6 on 2020-06-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0022_mentors_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='summary',
            field=models.CharField(default='no summary', max_length=1000),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='text',
            field=models.CharField(default='no text', max_length=8000),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
