# Generated by Django 3.0.6 on 2020-06-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0023_auto_20200609_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='summary',
            field=models.CharField(default='no summary', max_length=500),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='text',
            field=models.TextField(default='no text', max_length=8000),
        ),
    ]
