# Generated by Django 3.0.6 on 2020-06-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0024_auto_20200609_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='ids',
            field=models.TextField(default='no id', max_length=10),
        ),
    ]
