# Generated by Django 3.0.6 on 2020-06-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0025_auto_20200609_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='skill_level',
            field=models.CharField(default='{}', max_length=300),
        ),
        migrations.AlterField(
            model_name='mentors',
            name='skills',
            field=models.CharField(default='[]', max_length=300),
        ),
    ]
