# Generated by Django 3.0.6 on 2020-06-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0026_auto_20200610_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='mentor_assigned',
            field=models.CharField(default='no mentor assigned', max_length=100),
        ),
    ]
