# Generated by Django 3.0.6 on 2020-06-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0029_auto_20200611_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='summary',
            field=models.TextField(default='no summary', max_length=4000),
        ),
    ]
