# Generated by Django 3.0.6 on 2020-06-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0031_auto_20200611_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='extracted_skills',
            field=models.CharField(default='[]', max_length=300),
        ),
    ]
