# Generated by Django 3.0.6 on 2020-06-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0032_mentors_extracted_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='category',
            field=models.CharField(blank=True, default='no text', max_length=500),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='svm_categories',
            field=models.CharField(blank=True, default='no svm categories', max_length=200),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(default='no title', max_length=500),
        ),
    ]
