# Generated by Django 3.0.6 on 2020-06-15 09:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0033_auto_20200613_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='images_c',
            field=cloudinary.models.CloudinaryField(default='default.jpeg', max_length=255, verbose_name='avatar'),
            preserve_default=False,
        ),
    ]
