# Generated by Django 3.0.6 on 2020-06-15 13:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0034_mentors_images_c'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentors',
            name='images_c',
        ),
        migrations.AlterField(
            model_name='mentors',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='avatar'),
        ),
    ]
