# Generated by Django 3.0.6 on 2020-06-15 13:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0035_auto_20200615_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentors',
            name='resume',
            field=cloudinary.models.CloudinaryField(default='default.pdf', max_length=255, verbose_name='resume'),
            preserve_default=False,
        ),
    ]
